### ISSUE TITLE
Crear CNAME

### ISSUE THREAD

**Issue by diegobeauroyre** [jajs1975/jajs1975.github.io#10]
Hacer un .txt llamado 'CNAME' con:

ogpsummit.org

Debe estar en el root del repositorio.

**Comment by jajs1975** [comment]
Listo

**Comment by jajs1975** [comment]
Ya lo tengo agregado, en este momento no lo puse porque espero sean corregidos todos los issues y validados, para por último agregar este archivo de redireccionamiento.
