### ISSUE TITLE
Abrir signo de interrogación

### ISSUE THREAD

**Issue by diegobeauroyre** [jajs1975/jajs1975.github.io#7]
![screen shot 2015-06-05 at 5 24 59 pm](https://cloud.githubusercontent.com/assets/6226604/8016336/d5e8d9a0-0ba7-11e5-979a-9b335f3bdf4d.png)

**Comment by jajs1975** [comment]
Listo

**Comment by diegobeauroyre** [comment]
perdón, se me pasó que falta agregar un a 

"Escríbenos a hola@gobabierto.mx" ¿Podemos poner también un:

<a href="mailto:hola@gobabierto.mx?Subject=Hola%20again" target="_top">hola@gobabierto.mx</a>

**Comment by jajs1975** [comment]
Claro...lo agregamos..

**Comment by jajs1975** [comment]
Listo.
