### ISSUE TITLE
Poner Favicon y HEAD

### ISSUE THREAD

**Issue by diegobeauroyre** [jajs1975/jajs1975.github.io#8]
![screen shot 2015-06-05 at 5 20 43 pm](https://cloud.githubusercontent.com/assets/6226604/8016342/df8e9db4-0ba7-11e5-9ac7-9b37b92c4654.png)

El head sería: OGP Summit | Cumbre Global AGA | MX 2015 
Les pongo el favicon más adelante

**Comment by jajs1975** [comment]
Listo

**Comment by diegobeauroyre** [comment]
![ogpsummit](https://cloud.githubusercontent.com/assets/6226604/8017022/ab902fd2-0bb1-11e5-9a1f-c6a1c51b314e.png)
![ogpsummit2](https://cloud.githubusercontent.com/assets/6226604/8017023/ab915e16-0bb1-11e5-81b0-96ab12349e0f.png)

Van los favicons

**Comment by diegobeauroyre** [comment]
Les mandé de 16x y 32x porque 32 es mejor calidad, pero no se por qué hemos tenido problemas para que aparezca en unos navegadores. Lo seguro es 16 pero si lo pueden arreglar está buenísimo.

:100:

**Comment by jajs1975** [comment]
Ok...con gusto lo revisamos..

**Comment by jajs1975** [comment]
Listo.
