### ISSUE TITLE
Animación de español debe tener mismo formato que inglés

### ISSUE THREAD

**Issue by diegobeauroyre** [jajs1975/jajs1975.github.io#9]
![screen shot 2015-06-05 at 5 19 10 pm](https://cloud.githubusercontent.com/assets/6226604/8016375/31c4e7b4-0ba8-11e5-8ff2-4cc02216fefa.png)

**Comment by jajs1975** [comment]
Este issue no me quedó claro de que se trata, lo que hice fue ponerlo en color verde, como los demas.
Favor de validar.

**Comment by jajs1975** [comment]
Listo, creo..

**Comment by jipster** [comment]
@jajs1975 sigue habiendo diferencias en la animación

Faltan dos elementos: Aparta la Fecha y México | 2015
Cambio de estilo: Cumbre Global y abajo Alianza para el Gobierno Abierto (en negro y en dos líneas)
![image](https://cloud.githubusercontent.com/assets/5718530/8112317/a2eef582-102c-11e5-853b-137f92384332.png)
![image](https://cloud.githubusercontent.com/assets/5718530/8112322/a996a22c-102c-11e5-9bb8-9f8d1c7cb0cb.png)
![image](https://cloud.githubusercontent.com/assets/5718530/8112370/ea9bad3a-102c-11e5-84bb-de56b20feb64.png)
![image](https://cloud.githubusercontent.com/assets/5718530/8112378/fd590ac6-102c-11e5-8ef1-852351902c54.png)
